
services:
  django:
    build:
      context: ./requirements/django
      dockerfile: Dockerfile
    image: django:transcendence
    container_name: django
    restart: on-failure:10
    ports:
      - "8080:8000"
