
volumes:
  volume-django:
    name: volume-django
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/volume-django

services:
  django:
    build:
      context: ./requirements/django
      dockerfile: Dockerfile
    image: django:transcendence
    container_name: django
    restart: on-failure:10
  # Binds the HOST ~/data/volume-django -> CONTAINER /usr/src/app/ft_transcendence folder.
    volumes:
      - volume-django:/usr/src/app
    ports:
      - "8080:8000"
