
volumes:
  volume-django:
    name: volume-django
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${HOME}/data/volume-django

services:
  django:
    build:
      context: ./requirements/django
      dockerfile: Dockerfile
    image: django:transcendence
    container_name: django
    restart: on-failure:10
  # Binds the HOST ~/data/volume-django -> CONTAINER /usr/src/app/ft_transcendence folder.
    volumes:
      - volume-django:/usr/src/app
    ports:
      - "8080:8000"

  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:transcendence
    container_name: nginx
    restart: on-failure:10
    ports:
    - "10000:80"

  postgresql:
    build:
      context: ./requirements/postgresql
      dockerfile: Dockerfile
      args:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    image: postgresql:transcendence
    container_name: postgresql
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
